### ISSUE TITLE
Investigate options for passing URLs used throughout package functions

### ISSUE THREAD

**Issue by mmulvahill** [KechrisLab/multiMiR#2]
Currently uses a variable local to the package environment.  Using getOption to access and options("" = ...) to set may be advantageous in that it:
1.  formalizes the URLs as key package options 
2. allows the user to update the URL (universally across the R session) without requiring a new package release
3. prevents confusion over local vs package environment variable

```{r}
# 2. 
options("multimir_URL" = "https://new-mm-url.edu")
multimir_dbInfo()  # Still works without passing the new URL each time
```

```{r}
# 3.
multimir_URL  # Variable found in package environment
# [1] "http://multimir.ucdenver.edu/cgi-bin/multimir.pl"
multimir_URL <- "test"  # User attempt to update value places it in local environment
multimir_URL      # User/global environment
# [1] "test"
multiMiR::multimir_URL # But actual value used in functions (package env) is unchanged
# [1] "http://multimir.ucdenver.edu/cgi-bin/multimir.pl"
>
```

**Comment by smahaffey** [comment]
I have completed the changes needed to allow using previous or future database versions from one version of the package:

1. I have added multimir_dbInfoVersions() which gets the version list along with pertinent info.  

1. I have added a method to switch the database version being used.  It will display an error message if the switch is unsuccessful.  Likely due to wrong version string or server availability.

1. I've changed the initial setup to request a list of versions and setup to use the most current version.  Welcome message displays info about version/updated date or error message if server is unavailable at the moment.

1. Options for file names for the db schema and the rda file will be loaded from the DB since they are tied to the DB version.

@mmulvahill - I don't have permission to push the changes to GitHub. Also I can't actually get it to build as a package now so I can't fully test it as a package, but testing the methods seems to work.  I do not understand the issue I get an error about doc/index.html not existing if I build or try to tar/gzip and install it directly.  Any ideas on fixing this error so I can finish testing my changes.

**Comment by smahaffey** [comment]
I added a parameter for the list of tables.  MySQL seems really slow listing tables and this gets called repeatedly.  This should speed everything up.

**Comment by mmulvahill** [comment]
@smahaffey Thanks for implementing the db version change feature -- It looks great.

Quick FYI -- I'm currently about halfway through refactoring the package to reduce duplicate code, maintainence overhead, and make the pkg structure more consistent with 'best practices'.  As a part of this, I'm deprecating all function arguments that are set by our new global options (mostly `url`).   The idea being that the user should be able to change structural options for accessing the webserver in a consistent way, but it should be hidden for typical usage.
