### ISSUE TITLE
db.info

### ISSUE THREAD

**Issue by c2c12** [KechrisLab/multiMiR#29]
This database is truly amazing!
I'm already working with it for a while. I just noticed that despite using the db_version = "2.2.0"  I have a db.info table for the previous version of the database. For example, db.info  shows that last release of TargetScan was 7.1 Jun, 2012.  According to your webpage, it should be a version from Jun, 2016.
I tried to reinstall the package couple of times and everything seems ok but this wrong table still appears. How I can be 100% sure that I'm working with the last release of the multiMiR? 2012 is way too much outdated. 
I'd be grateful for the help.

Zofia

[db_info_error.txt](https://github.com/KechrisLab/multiMiR/files/2612822/db_info_error.txt)

**Comment by smahaffey** [comment]
The database and R package are versioned separately now due to incorporating into bioconductor.  Are you using the current version of the R package (v1.4) in bioconductor? (http://bioconductor.org/packages/release/bioc/html/multiMiR.html)  The bioconductor package will default to the current database version where as the older package from the multiMiR site won't automatically update to database v2.2.  Please let us know if this is happening with the bioconductor version.

**Comment by c2c12** [comment]
Thank you for the fast response.
I'm using R version 3.5.1 (2018-07-02) -- "Feather Spray". I tested
downloading multiMir on two computers using tar file and command:
*if (!requireNamespace("BiocManager", quietly = TRUE))*
*    install.packages("BiocManager")*
*BiocManager::install("multiMiR", version = "3.8")*

In both cases, it installed version 1.4 and after loading library, it
printed that it uses Database Version: 2.2.0. Unfortunately, when I'm
checking db.info I still have an information for the older version with
targetscan from 2012.
Printscreen is enclosed.

**Comment by c2c12** [comment]
second part of the printscreen

**Comment by smahaffey** [comment]
Thank you for the additional information.    It does say targetscan v 7.1 which should have had a date of  June 2016.  The version was updated, but the year for the version was not updated as the previous release was 6.2 June 2012.  I update those rows manually with the release and I missed updating the year.  I'm very sorry about the confusion.  I have corrected it now.  Since this is pulled from our database the change should be reflected immediately.  Again sorry for the confusion this caused.  Thank you for bringing this to our attention.

**Comment by c2c12** [comment]
Thank you so much. This tool is really amazing please keep it available.
Best regards,
Zofia

**Comment by umitozorhan** [comment]
Dear Spencer Mahaffey @smahaffey ,

First of all, I want to thank you for your effort in R program MultiMiR. We are using these program as well as with other programs. I am pretty satisfied with the results however some of the databases are not up to date such as Diana microT, and targetscan. Is it possible to the update these databases as well as adding new databases as Diana micro-T CDS ? Moreover, I like the table format of results but it is hard to understand when we want to compare databases with each other. You know every database are using different criteria and giving results in different formats. Is it possible to implement a new feature about targets of given miRNAs that came from databases ?
Example:
miRNA   Target Name Number Of Databases Show this target as a target
hsa-let-7b  AKT           8

Thank you for your help and work. Have a nice day.

Kind Regards,
Ümit

**Comment by smahaffey** [comment]
@umitozorhan Thank you. I'm very sorry for the slow response.   I see targetscan has had a new release 7.2 and tarbase 8 is available.    We tried to get permission to update to tarbase 7 with our last update and could not get any response.  I don't see an update to DIANA microT CDS it is still on version 5.  

I will pass this on to the people responsible for planning maintenance of the package and see if we can try to update the multiMiR database with all of the newest database versions.

**Comment by umitozorhan** [comment]
Dear Spencer Mahaffey,
Thank you for response. I tried to reach tarbase team and they gave to
response below. May be it could work for you to update tarbase. I am
appreciated your effort on this. Thank you for work.

 We would like to thank you for your interest in DIANA-Tarbase v8 database.
Your application has been successfully processed. You can download the
dataset from the following link:
http://carolina.imis.athena-innovation.gr/diana_tools/downloads/e2de248e81009d5a5s33ebe9906fa32c/TarBase_v8_download.tar.gz
You will be automatically notified in case of a future major update.
We really value your feedback in order to substantially improve Tarbase v8.
If you have any questions regarding Tarbase v8 or the provided dataset,
please do not hesitate to contact us.

Best regards,
The Tarbase v8 Administration Team

Best regards,


*Ümit Özorhan*

*Graduate Student*

*Yeditepe University*
*Medical Biology*



Spencer Mahaffey <notifications@github.com>, 11 Oca 2019 Cum, 21:06
tarihinde şunu yazdı:

**Comment by smahaffey** [comment]
Thank you.  I have discussed a new database update with the PI.  We will work on one but I can't promise when it will be ready.  We will try to include all of the latest database releases available at the time.

I had missed your last question about providing a shorter summary.  We can look at that, but as I just learned we no longer have someone working on maintaining the R code.  If you can use PhenoGen(https://phenogen.org) either through the genome browser or gene lists on the miRNA tab of either a gene report or gene list tools. We are providing a summary that is close to what you are requesting.  We are just calling multiMiR and then providing a summary through the web interface.

**Comment by smahaffey** [comment]
MultiMiR Database v2.3 is ready and will be the default database soon in the bioconductor version of the package.  We will try to keep the current databases updated and we'll discuss including new databases for the next release.  I've started a new issue for adding Diana micro-T CDS.
